# Generated by Django 2.2.1 on 2019-06-03 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill_manager', '0004_auto_20190603_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='month',
        ),
    ]
