# Generated by Django 2.2.1 on 2019-06-05 11:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_manager', '0006_bill_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='month',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(201901), django.core.validators.MaxValueValidator(999912)]),
        ),
    ]
